"""Додано поле group_id до User з іменем обмеження

Revision ID: 0db8d0482ae8
Revises: dd9d6b2c116e
Create Date: 2025-02-15 17:25:47.702028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db8d0482ae8'
down_revision = 'dd9d6b2c116e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_group', 'groups', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_group', type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
