"""Fixed foreign key constraint in Announcement

Revision ID: 410efff0d6a3
Revises: a76bea736567
Create Date: 2025-02-15 15:31:23.041786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410efff0d6a3'
down_revision = 'a76bea736567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_announcement_category', 'announcement_categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_constraint('fk_announcement_category', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
