"""Додано teacher_id до subjects

Revision ID: a76bea736567
Revises: a2339b2712f0
Create Date: 2025-02-13 20:11:38.238611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76bea736567'
down_revision = 'a2339b2712f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('faculty_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('uploaded_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=False))
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_subject_teacher', 'users', ['teacher_id'], ['id'])

    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subject_teacher', type_='foreignkey')
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('teacher_id')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('uploaded_by',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('faculty_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
